export const ALL_INSPECTION_ITEMS: Vehicle.InspectionChecklistItem[] = [
    // --- ELEMENTY CODZIENNE / PRZED ZMIANĄ ---
    {
        categoryKey: 'photo_dashboard',
        label: 'Zdjęcie deski rozdzielczej',
        description: 'Wyraźne zdjęcie pokazujące przebieg (odometr) oraz poziom paliwa/naładowania',
        frequency: 'daily',
        requiresPhoto: true,
        isMandatory: true,
    },
    {
        categoryKey: 'photo_front',
        label: 'Zdjęcie przodu pojazdu',
        description: 'Zdjęcie obejmujące przedni zderzak, maskę i reflektory',
        frequency: 'daily',
        requiresPhoto: true,
        isMandatory: true,
    },
    {
        categoryKey: 'photo_rear',
        label: 'Zdjęcie tyłu pojazdu',
        description: 'Zdjęcie obejmujące klapę bagażnika, tylny zderzak i światła',
        frequency: 'daily',
        requiresPhoto: true,
        isMandatory: true,
    },
    {
        categoryKey: 'photo_left_side',
        label: 'Zdjęcie lewej strony',
        description: 'Pełne zdjęcie lewej strony pojazdu (drzwi, błotniki i koła)',
        frequency: 'daily',
        requiresPhoto: true,
        isMandatory: true,
    },
    {
        categoryKey: 'photo_right_side',
        label: 'Zdjęcie prawej strony',
        description: 'Pełne zdjęcie prawej strony pojazdu (drzwi, błotniki i koła)',
        frequency: 'daily',
        requiresPhoto: true,
        isMandatory: true,
    },
    {
        categoryKey: 'tires',
        label: 'Stan i ciśnienie w oponach',
        description: 'Wizualna kontrola spadek ciśnienia lub flaka; kontrolka TPMS wyłączona',
        frequency: 'daily',
        requiresPhoto: false,
        isMandatory: true,
    },
    {
        categoryKey: 'cleanliness',
        label: 'Czystość wnętrza',
        description: 'Fotele i wycieraczki czyste, wolne od śmieci i nieprzyjemnych zapachów',
        frequency: 'daily',
        requiresPhoto: false,
        isMandatory: true,
    },
    {
        categoryKey: 'lost_property',
        label: 'Rzeczy zostawione przez pasażerów',
        description: 'Sprawdzono, czy w pojeździe nie ma przedmiotów zgubionych podczas poprzedniej zmiany',
        frequency: 'daily',
        requiresPhoto: false,
        isMandatory: true,
    },
    {
        categoryKey: 'dashboard_alerts',
        label: 'Kontrolki ostrzegawcze',
        description: 'Brak aktywnych kontrolek błędów (Engine, ABS, Airbag, Brakes)',
        frequency: 'daily',
        requiresPhoto: false,
        isMandatory: true,
    },

    // --- ELEMENTY MIESIĘCZNE ---
    {
        categoryKey: 'lighting',
        label: 'Oświetlenie i kierunkowskazy',
        description: 'Wszystkie światła mijania, drogowe, stopu i kierunkowskazy są sprawne',
        frequency: 'monthly',
        requiresPhoto: false,
        isMandatory: true,
    },
    {
        categoryKey: 'safety_gear',
        label: 'Wyposażenie awaryjne i BHP',
        description: 'Kamizelka odblaskowa, trójkąt ostrzegawczy i apteczka są na wyposażeniu',
        frequency: 'monthly',
        requiresPhoto: false,
        isMandatory: true,
    },
    {
        categoryKey: 'fluids',
        label: 'Poziomy płynów eksploatacyjnych',
        description: 'Poziom oleju, płynu chłodniczego, hamulcowego i spryskiwaczy między MIN a MAX',
        frequency: 'monthly',
        requiresPhoto: false,
        isMandatory: true,
    },
    {
        categoryKey: 'brakes',
        label: 'Stan klocków i tarcz hamulcowych',
        description: 'Grubość klocków hamulcowych zweryfikowana powyżej limitu bezpieczeństwa (>3mm)',
        frequency: 'monthly',
        requiresPhoto: false,
        isMandatory: true,
    },
    {
        categoryKey: 'documentation',
        label: 'Dokumenty i wypisy w pojeździe',
        description: 'Dowód rejestracyjny, ubezpieczenie OC/AC oraz wypis z licencji w schowku',
        frequency: 'monthly',
        requiresPhoto: false,
        isMandatory: true,
    },
];